"""Initial migration

Revision ID: 73d23ce0344f
Revises: 
Create Date: 2026-02-16 13:40:43.103050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d23ce0344f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_username'), 'profiles', ['username'], unique=True)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_title'), 'plans', ['title'], unique=False)
    op.create_table('macrocycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macrocycles_id'), 'macrocycles', ['id'], unique=False)
    op.create_index(op.f('ix_macrocycles_name'), 'macrocycles', ['name'], unique=False)
    op.create_table('microcycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('macrocycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['macrocycle_id'], ['macrocycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_microcycles_id'), 'microcycles', ['id'], unique=False)
    op.create_index(op.f('ix_microcycles_name'), 'microcycles', ['name'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('perceived_exertion', sa.Integer(), nullable=True),
    sa.Column('microcycle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['microcycle_id'], ['microcycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_description'), 'sessions', ['description'], unique=False)
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_description'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_microcycles_name'), table_name='microcycles')
    op.drop_index(op.f('ix_microcycles_id'), table_name='microcycles')
    op.drop_table('microcycles')
    op.drop_index(op.f('ix_macrocycles_name'), table_name='macrocycles')
    op.drop_index(op.f('ix_macrocycles_id'), table_name='macrocycles')
    op.drop_table('macrocycles')
    op.drop_index(op.f('ix_plans_title'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_profiles_username'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###
